### ISSUE TITLE
Create initial interscript website

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.com#1]
1. Landing page + description, lists out all available transliteration systems (obtainable via api.interscript.com, see https://github.com/interscript/interscript-api#listing-supported-systems)

2. A frontend for a remote API (lambda) to allow returning a transliterated string.
(via https://github.com/interscript/interscript-api#transliterating-text)

Ping @strogonoff

**Comment by ronaldtse** [comment]
The API URL is currently https://zkjrxjsleh.execute-api.us-east-1.amazonaws.com/prod/interscript but it will be set to api.interscript.com soon (when https://github.com/interscript/interscript-api/issues/7 is done)

**Comment by strogonoff** [comment]
Initial stub is done per https://github.com/interscript/interscript.com/commit/aea535d7eebfa0079cde5b799a35d2fb27bf73b1

**Comment by strogonoff** [comment]
Next:

* Interscript-specific stuff: interactive transliteration demo
* Move parts that apply to all websites to the new “Open Project” project
* Improve nav (highlight current item, support multiple pages, parse adoc instead of fetching GitHub’s Markdown HTML, etc.)

**Comment by ronaldtse** [comment]
Thank you @strogonoff !

**Comment by ronaldtse** [comment]
Closing in favor of the new tasks #2 #3 #4
