### ISSUE TITLE
Improve demo: fetch supported systems from API

### ISSUE THREAD

**Issue by strogonoff** [interscript/interscript.com#16]
Implementation was rolled, so this task still stands:

Systems were hard-coded[0] while API was under development and were left in that state.

To fix this, the following is needed:

* Update [LiveDemo](https://github.com/interscript/interscript.com/blob/master/src/containers/Landing.tsx#L79) component to get a list of systems using API (using `axios`, see [another API call for an example](https://github.com/interscript/interscript.com/blob/master/src/containers/Landing.tsx#L112). This should happen in `useEffect()` in the beginning of component lifecycle. Make sure the list is in the same format as in [0], and pass it as a prop to `SystemSelector`.

* Update [SystemSelector](https://github.com/interscript/interscript.com/blob/master/src/components/SystemSelector.tsx#L41) component to accept a conversion systems as a list via a prop (instead of having them hard-coded[0]).

I can take it later or perhaps someone wants to try a React task, this could be a good first one (I’ll leave myself assigned and review the PR).

[0] See https://github.com/interscript/interscript.com/blob/master/src/components/SystemSelector.tsx#L41

**Comment by ronaldtse** [comment]
@strogonoff is this task already completed? Thanks.
