### ISSUE TITLE
Language code `mkd` stands for Macedonian in ISO 639

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.com#5]
<img width="357" alt="Screen Shot 2020-08-11 at 10 56 08 AM" src="https://user-images.githubusercontent.com/11865/89852364-43bf4100-dbc1-11ea-822f-c155e71e355b.png">

<img width="431" alt="Screen Shot 2020-08-11 at 10 55 58 AM" src="https://user-images.githubusercontent.com/11865/89852357-3e61f680-dbc1-11ea-9f8d-4fc5c255f198.png">

**Comment by strogonoff** [comment]
(This was fixed some time in 1st half of August)
